[package]
name = "policy_algebra"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alga = { version = "0.9.3", default-features = false }
alga_derive = { version = "0.9.2", default-features = false }
