[package]
name = "policy_proc_macro"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Import the AST tree.
policy_core = { path = "../policy_core" }
proc-macro2 = "1.0.64"
quote = "1.0.27"
syn = { version = "2.0.16", features = ["full"] }

[lib]
proc-macro = true
doctest = false

[dev-dependencies]
policy_carrying_data = { path = "../policy_carrying_data" }
policy_core = { path = "../policy_core" }
policy_execution = { path = "../policy_execution" }
