[package]
name = "policy_execution"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["use-sql", "built-in"]
# Enable support for SQL.
use-sql = []
read-fs = ["policy_carrying_data/read-fs"]
# Support for module-like executor set.
modular = ["policy_ffi/modular"]
static = ["policy_ffi/static"]
built-in = []
# Enable the support for RPC.
rpc = []

[dependencies]
bitflags = "2.3.2"
hashbrown = { version = "0.14.0", features = ["serde"] }
log = "0.4.19"
policy_carrying_data = { path = "../policy_carrying_data" }
policy_core = { path = "../policy_core" }
policy_ffi = { path = "../policy_ffi" }
policy_utils = { path = "../policy_utils" }
serde = { version = "1.0.166", features = ["rc", "derive"] }
serde_json = "1.0.99"
sqlparser = { version = "0.35.0", features = ["serde", "visitor"] }
typetag = "0.2.8"
