[package]
name = "policy_carrying_data"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["prettyprint"]
prettyprint = ["papergrid"]

[dependencies]
opendp = "0.7.0"
policy_core = { path = "../policy_core" }
predicates = "3.0.3"
papergrid = { version = "0.9.0", optional = true }

[lib]
doctest = false
