[package]
name = "policy_ffi"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
modular = ["libloading", "lazy_static", "hashbrown"]
static = []

[dependencies]
hashbrown = { version = "0.14.0", features = ["serde"], optional = true }
lazy_static = { version = "1.4.0", optional = true }
libloading = { version = "0.8.0", optional = true }
policy_core = { path = "../policy_core" }
serde_json = "1.0.99"

[build-dependencies]
rustc_version = "0.2"
