[package]
name = "executor_lib"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
policy_carrying_data = { path = "../../../policy_carrying_data" }
policy_core = { path = "../../../policy_core" }
policy_execution = { path = "../../../policy_execution" }
policy_privacy = { path = "../../../policy_privacy" }
policy_utils = { path = "../../../policy_utils" }
serde_json = "1.0.99"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]
bench = false

[build-dependencies]
rustc_version = "0.2"
